### ISSUE TITLE
怎么做到，发送字符不转码呢？

### ISSUE THREAD

**Issue by wx409790282** [Zvirtuey/AndroidSocket#2]
现在sendStrData发送过去的字符串的decode，例如发送 12  服务器接收到的是  31 32，那假如我自定义的命令格式，要发送一个例如  AA BB CC这样的字符串给服务器，该怎么做呢，谢谢。

**Comment by Zvirtuey** [comment]
这些可以通过客户端与服务端的协议协商，比如你要给字段name的值是AA BB CC，服务器解析的时候就用字符串的方式接收，如果你想给服务器12的整型，服务端解析解析时按整型接收，如果是"12"，服务端就用字符串接收，客户端发送的数据都是以二进制形式的给服务器的，就看服务器怎么解析！
