### ISSUE TITLE
有bug，程序直接崩溃了

### ISSUE THREAD

**Issue by jtttl** [Zvirtuey/AndroidSocket#5]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.virtue.socketlibrary.utils.ResponseListener.onFail(int)' on a null object reference
        at com.virtue.socketlibrary.manager.Socketer$SendMsgThread$1.handleMessage(Socketer.java:535)

**Comment by Zvirtuey** [comment]
新版1.0.7已修复，谢谢支持！
